<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class DocumentsUserHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = $value instanceof \MongoId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['email']) || (! empty($this->class->fieldMappings['email']['nullable']) && array_key_exists('email', $data))) {
            $value = $data['email'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['email']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['email']->setValue($document, $return);
            $hydratedData['email'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['password']) || (! empty($this->class->fieldMappings['password']['nullable']) && array_key_exists('password', $data))) {
            $value = $data['password'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['password']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['password']->setValue($document, $return);
            $hydratedData['password'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['nickname']) || (! empty($this->class->fieldMappings['nickname']['nullable']) && array_key_exists('nickname', $data))) {
            $value = $data['nickname'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['nickname']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['nickname']->setValue($document, $return);
            $hydratedData['nickname'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['faction']) || (! empty($this->class->fieldMappings['faction']['nullable']) && array_key_exists('faction', $data))) {
            $value = $data['faction'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['faction']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['faction']->setValue($document, $return);
            $hydratedData['faction'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['description']) || (! empty($this->class->fieldMappings['description']['nullable']) && array_key_exists('description', $data))) {
            $value = $data['description'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['description']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['description']->setValue($document, $return);
            $hydratedData['description'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['salt']) || (! empty($this->class->fieldMappings['salt']['nullable']) && array_key_exists('salt', $data))) {
            $value = $data['salt'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['salt']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['salt']->setValue($document, $return);
            $hydratedData['salt'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['token']) || (! empty($this->class->fieldMappings['token']['nullable']) && array_key_exists('token', $data))) {
            $value = $data['token'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['token']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['token']->setValue($document, $return);
            $hydratedData['token'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['dateCreated'])) {
            $value = $data['dateCreated'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->reflFields['dateCreated']->setValue($document, clone $return);
            $hydratedData['dateCreated'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['score']) || (! empty($this->class->fieldMappings['score']['nullable']) && array_key_exists('score', $data))) {
            $value = $data['score'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['score']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['score']->setValue($document, $return);
            $hydratedData['score'] = $return;
        }

        /** @Many */
        $mongoData = isset($data['words']) ? $data['words'] : null;
        $return = $this->dm->getConfiguration()->getPersistentCollectionFactory()->create($this->dm, $this->class->fieldMappings['words']);
        $return->setHints($hints);
        $return->setOwner($document, $this->class->fieldMappings['words']);
        $return->setInitialized(false);
        if ($mongoData) {
            $return->setMongoData($mongoData);
        }
        $this->class->reflFields['words']->setValue($document, $return);
        $hydratedData['words'] = $return;

        /** @Many */
        $mongoData = isset($data['wordFavs']) ? $data['wordFavs'] : null;
        $return = $this->dm->getConfiguration()->getPersistentCollectionFactory()->create($this->dm, $this->class->fieldMappings['wordFavs']);
        $return->setHints($hints);
        $return->setOwner($document, $this->class->fieldMappings['wordFavs']);
        $return->setInitialized(false);
        if ($mongoData) {
            $return->setMongoData($mongoData);
        }
        $this->class->reflFields['wordFavs']->setValue($document, $return);
        $hydratedData['wordFavs'] = $return;
        return $hydratedData;
    }
}